Implement Occasion calculation
metrumresearchgroup/lastdose pull request #49
Opened 2024-12-20 16:55 UTC by kylebaron

2025-01-08 18:42 UTC, kylebaron commented
Check behavior for commented doses.

2025-01-22 13:40 UTC, kylebaron commented
Thanks for help with `stringsAsFactors` again, @kyleam.

2025-01-28 13:01 UTC, kylebaron commented
Waiting on @andersone1 @graceannobrien @michaelmcd18 to review behavior and either confirm or propose alternate behavior.

2025-02-21 12:42 UTC, kylebaron commented
@kyleam This is ready for review; I'd be happy to talk through any of the C++ code.

2025-02-21 16:42 UTC, kyleam requested changes
Some of the conceptual details you laid out in the PR description are a bit beyond me, but it looks like you did a very thorough job of documenting those in `inst/test-data/occ/occ-data.R`, the `lastdose` docstring, and `tests/testthat/test-occ.R`.

Aside from my few comments inline, this looks good to me code-wise (and inline with what I expect from inspecting the surrounding code).

2025-02-21 16:42 UTC, kyleam commented on inst/test-data/occ/occ-data.R
> +  file <- here("inst/data/occ/", file)
This should now be `inst/test-data/occ/` to account for the rename in 4d05903 (rename data directory, 2025-01-02).

2025-02-21 16:42 UTC, kyleam commented on R/lastdose.R
> +#' used for the [lastdose()] function.
> only used for the [lastdose()] function

I think this is a pasto from `include_tafd` that isn't accurate for `include_occ`. Unlike `include_tafd`, `include_occ` is also an argument to `lastdose_list()` (and by extension, `lastdose_df` because it passes its `...` to `lastdose_list`).

2025-02-21 16:42 UTC, kyleam commented on R/lastdose.R
>    ans <- lastdose_list(data, ...)
Should `lastdose` pass `include_occ` to `lastdose_list`? It's not strictly necessary due to the `include_occ` condition on line 153, but it'd prevent `lastdose_impl` from doing unnecessary work to generate `occ` just for it to be discarded.

2025-02-21 16:42 UTC, kyleam commented on tests/testthat/test-occ.R
> +test_that("OCC multi-dose, explicit", {
Should something like "no obs" be appended to these two descriptions to distinguish them from the test blocks above with the same names?

2025-02-25 13:45 UTC, kylebaron commented on R/lastdose.R
>    ans <- lastdose_list(data, ...)
Thanks; agree and I think I was aiming for that, but got wires crossed for what was going where.

2025-02-25 14:20 UTC, kyleam approved these changes
Updates look good to me, thanks.

(I know my [comment](https://github.com/metrumresearchgroup/lastdose/pull/49#discussion_r1965849222) about colliding test descriptions is still unresolved, but that's not blocking.)

2025-02-25 15:22 UTC, kylebaron commented on tests/testthat/test-occ.R
> +test_that("OCC multi-dose, explicit", {
Thanks; test names updated / clarified.

2025-02-25 16:18 UTC, kylebaron commented
All of @kyleam review comments have been resolved (I believe); only waiting on input from Metrum datascience (@andersone1 , @michaelmcd18 , @graceannobrien ) on behavior.

2025-03-21 11:19 UTC, merged